# Generated by Django 5.1.6 on 2025-02-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial", models.CharField(max_length=50, unique=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("height", models.FloatField()),
                ("horizontal_speed", models.FloatField()),
                ("vertical_speed", models.FloatField()),
                ("is_dangerous", models.BooleanField(default=False)),
                (
                    "danger_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
