# Generated by Django 5.1.6 on 2025-02-11 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drone",
            name="serial",
            field=models.CharField(max_length=21, unique=True),
        ),
        migrations.CreateModel(
            name="FlightPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "drone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flight_paths",
                        to="drones.drone",
                    ),
                ),
            ],
        ),
    ]
